# Generated by Django 3.0.4 on 2020-03-26 01:53

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=99)),
                ('last_name', models.CharField(max_length=99)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'None of above')], default='M', max_length=1)),
                ('phone_number', models.CharField(max_length=99, validators=[register.models.validate_phone_number])),
                ('email', models.CharField(db_index=True, max_length=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=30)),
                ('cpf', models.CharField(db_index=True, max_length=30, validators=[register.models.validate_cnpj])),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
