# Generated by Django 2.1.4 on 2018-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181213_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('nome',), 'verbose_name': 'produto'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descricao'),
        ),
    ]
